//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokanApp.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SiteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DokanApp.App_GlobalResources.SiteResource", typeof(SiteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58 Street, Next to Naif Hamad Al Dabbous Mosque, Hur Compound, Homoud Abdulaziz Al Senan St, Fahaheel, Kuwait.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        public static string All_Categories {
            get {
                return ResourceManager.GetString("All_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby.
        /// </summary>
        public static string baby {
            get {
                return ResourceManager.GetString("baby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boy.
        /// </summary>
        public static string boy {
            get {
                return ResourceManager.GetString("boy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boys Collection.
        /// </summary>
        public static string Boys_Collection {
            get {
                return ResourceManager.GetString("Boys_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string contactus {
            get {
                return ResourceManager.GetString("contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer.
        /// </summary>
        public static string designer {
            get {
                return ResourceManager.GetString("designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KWD.
        /// </summary>
        public static string Dinar {
            get {
                return ResourceManager.GetString("Dinar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        public static string Dollar {
            get {
                return ResourceManager.GetString("Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dresses.
        /// </summary>
        public static string Dresses {
            get {
                return ResourceManager.GetString("Dresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girl.
        /// </summary>
        public static string girl {
            get {
                return ResourceManager.GetString("girl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girls Collection.
        /// </summary>
        public static string Girls_Collection {
            get {
                return ResourceManager.GetString("Girls_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewellery &amp; Watches.
        /// </summary>
        public static string Jewel_Watches {
            get {
                return ResourceManager.GetString("Jewel_Watches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Collections.
        /// </summary>
        public static string Latest_Collections {
            get {
                return ResourceManager.GetString("Latest_Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login / Signup.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightwear.
        /// </summary>
        public static string Nightwear {
            get {
                return ResourceManager.GetString("Nightwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality You Can Trust.
        /// </summary>
        public static string Service1Head {
            get {
                return ResourceManager.GetString("Service1Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We promise to put quality first and bring you only top brands, in practically new condition..
        /// </summary>
        public static string Service1Text {
            get {
                return ResourceManager.GetString("Service1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Delivery.
        /// </summary>
        public static string Service2Head {
            get {
                return ResourceManager.GetString("Service2Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliable door-to-door delivery of your time-sensitive shipments within only hours..
        /// </summary>
        public static string Service2Text {
            get {
                return ResourceManager.GetString("Service2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24/7 Support.
        /// </summary>
        public static string Service3Head {
            get {
                return ResourceManager.GetString("Service3Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round-the-clock assistance for a smooth shopping experience..
        /// </summary>
        public static string Service3Text {
            get {
                return ResourceManager.GetString("Service3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Value.
        /// </summary>
        public static string Service4Head {
            get {
                return ResourceManager.GetString("Service4Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer competitive prices on our 100 million plus product range..
        /// </summary>
        public static string Service4Text {
            get {
                return ResourceManager.GetString("Service4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe Payment.
        /// </summary>
        public static string Service5Head {
            get {
                return ResourceManager.GetString("Service5Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with the most popular and secure payment methods..
        /// </summary>
        public static string Service5Text {
            get {
                return ResourceManager.GetString("Service5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoes.
        /// </summary>
        public static string shoes {
            get {
                return ResourceManager.GetString("shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        public static string shoppingCart {
            get {
                return ResourceManager.GetString("shoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swimwear.
        /// </summary>
        public static string Swimwear {
            get {
                return ResourceManager.GetString("Swimwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ties &amp; Bow Ties.
        /// </summary>
        public static string TiesnBowTies {
            get {
                return ResourceManager.GetString("TiesnBowTies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underwear.
        /// </summary>
        public static string Underwear {
            get {
                return ResourceManager.GetString("Underwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish List.
        /// </summary>
        public static string Wishlist {
            get {
                return ResourceManager.GetString("Wishlist", resourceCulture);
            }
        }
    }
}
