//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokanApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public int BrandID { get; set; }
        public string BrandName { get; set; }
        public string BrandNameAR { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
