//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokanApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCard
    {
        public int CardTypeID { get; set; }
        public string CardTypename { get; set; }
        public string CardTypeNameAR { get; set; }
        public string CardLogo { get; set; }
    }
}
