//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokanApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int ProductId { get; set; }
        public Nullable<int> ProductMasterID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int SizeId { get; set; }
        public int ColorId { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string SKUID { get; set; }
        public string ProductName { get; set; }
        public string ProductNameAr { get; set; }
        public string ProductDesc { get; set; }
        public string ProductDescAr { get; set; }
        public string ImagePath { get; set; }
        public double MSRP { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<int> Ranking { get; set; }
        public bool ProductAvailable { get; set; }
        public string CurrentOrder { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ProductMaster ProductMaster { get; set; }
    }
}
