//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokanApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductMaster()
        {
            this.ProductDetails = new HashSet<ProductDetail>();
        }
    
        public int ProductMasterID { get; set; }
        public string MasterName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Ranking { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string imagepath { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public int SubCategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
