//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokanApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int RegId { get; set; }
        public string FullName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Area { get; set; }
        public string Country { get; set; }
        public int Contact { get; set; }
        public Nullable<int> Acontact { get; set; }
        public string GoogleCo { get; set; }
        public string ShipAddress { get; set; }
        public Nullable<int> ShipContact { get; set; }
        public Nullable<int> CreditCardNmbr { get; set; }
        public string CreditCardTypeID { get; set; }
        public Nullable<System.DateTime> CreditCardExpMo { get; set; }
        public Nullable<System.DateTime> CreditCardExpYr { get; set; }
        public Nullable<System.DateTime> DateJoined { get; set; }
        public bool Isdeleted { get; set; }
    }
}
